name: Build
on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        preset:
          - Debug - MSVC
          - Debug - clang-cl
          - Release
    name: "${{matrix.preset}}"
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}/.vcpkg-binary-cache
    steps:
      - name: Set up visual studio environment
        shell: pwsh
        run: |
          $VSRoot = $(
            vswhere `
              -latest `
              -products * `
              -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
              -property installationPath)
          cmd /c "`"${VSRoot}/VC/Auxiliary/Build/vcvarsall.bat`" x64&set" `
            | Where-Object { $_ -like '*=*' } `
            | Out-File -Encoding utf8 -Append $Env:GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup vcpkg binary cache
        uses: actions/cache@v4
        with:
          key: vcpkg-${{matrix.preset}}-${{hashFiles('vcpkg.json', 'vcpkg-configuration.json')}}
          path: ${{env.VCPKG_DEFAULT_BINARY_CACHE}}
      - name: Configure
        id: configure
        shell: pwsh
        run: |
          New-Item -Type directory -Force "${{env.VCPKG_DEFAULT_BINARY_CACHE}}"
          New-Item -Type directory build
          cd build
          cmake .. --preset "${{matrix.preset}}" `
            "-DVERSION_TWEAK_PREFIX=GHA." `
            "-DVERSION_TWEAK=${{github.run_number}}"
          echo "VersionQuad=$(Get-Content version-quad.txt)" | Out-File -Encoding utf8 -Append $Env:GITHUB_OUTPUT
      - name: Build
        working-directory: build
        run: cmake --build . --parallel
      - name: Upload artifacts
        if: matrix.preset == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: "OpenKneeboard-Fresh-Start-v${{steps.configure.outputs.VersionQuad}}"
          path: |
            build/src/OpenKneeboard-Fresh-Start.exe
            build/src/OpenKneeboard-Fresh-Start.pdb
